source/api_v1/urls.py
from django.urls import include, path
from rest_framework import routers
from api_v1.views import CommentViewSet, LikeViewSet

router = routers.DefaultRouter()
router.register(r'comments', CommentViewSet)
router.register(r'likes', LikeViewSet)


app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    # path('login/', name='api_token_auth'),
    # path('logout/',  name='api_token_delete')

]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/v1/', include('api_v1.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, PhotoView, AddPhoto, EditPhoto, DeletePhoto
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('photo/<int:pk>/', PhotoView.as_view(), name='photo_detail'),
    path('photo/add/', AddPhoto.as_view(), name='add_photo'),
    path('photo/<int:pk>/edit/', EditPhoto.as_view(), name='edit_photo'),
    path('photo/<int:pk>/delete/', DeletePhoto.as_view(), name='delete_photo'),
]

source/api_v1/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Photo(models.Model):
    photo = models.ImageField(upload_to='user_pics', verbose_name='Photo')
    note = models.CharField(max_length=50, verbose_name='Note')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Added date")
    like = models.IntegerField(default=0, verbose_name='Like')
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, verbose_name='Added by')

    def __str__(self):
        return self.note

    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'


class Comment(models.Model):
    text = models.TextField(max_length=200, verbose_name='Comment')
    photo = models.ForeignKey('Photo', on_delete=models.CASCADE, verbose_name='Photo', related_name='photo_comment')
    comment_author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, verbose_name='Added by')
    comment_created_at = models.DateTimeField(auto_now_add=True, verbose_name="Added date")

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'


class Like(models.Model):
    user = models.ForeignKey(User, related_name='like_author', on_delete=models.CASCADE, verbose_name='User')
    photo = models.ForeignKey('Photo', related_name='like_photo', on_delete=models.CASCADE, verbose_name='Photo')


    def __str__(self):
        return '{}, {}'.format(self.user, self.photo)

    class Meta:
        verbose_name = 'Like'
        verbose_name_plural = 'Likes'

source/api_v1/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from api_v1.serializer import CommentSerializer, LikeSerializer
from webapp.models import Comment, Like


class CommentViewSet(ModelViewSet):
    # permission_classes = IsAuthenticated
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def filter_queryset(self, queryset):
        queryset = super(CommentViewSet, self).filter_queryset(queryset)
        return queryset.order_by('-comment_created_at')


class LikeViewSet(ModelViewSet):
    queryset = Like.objects.all()
    serializer_class = LikeSerializer

source/webapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Photo


class IndexView(ListView):
    template_name = 'index.html'
    model = Photo
    context_object_name = 'photos'
    ordering = ['-created_at']

    def session(self, request):
        print(request.session.items())

class PhotoView(DetailView):
    model = Photo
    template_name = 'detail.html'
    context_object_name = 'photo'


class AddPhoto(LoginRequiredMixin, CreateView):
    model = Photo
    template_name = 'create.html'
    fields = ['photo', 'note', 'like']

    def form_valid(self, form):
        self.object = self.model.objects.create(author=self.request.user, ** form.cleaned_data)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:photo_detail', kwargs={'pk': self.object.pk})


class EditPhoto(UserPassesTestMixin, UpdateView):
    model = Photo
    template_name = 'edit.html'
    context_object_name = 'photo'
    fields = ['photo', 'note', 'like']


    def test_func(self, **kwargs):
        photo = Photo.objects.get(pk=self.kwargs.get('pk'))
        if self.request.user == photo.author or self.request.user.has_change_permission('webapp.change_photo'):
            return True
        else:
            return False

    def get_success_url(self):
        return reverse('webapp:photo_detail', kwargs={'pk': self.object.pk})


class DeletePhoto(UserPassesTestMixin, DeleteView):
    model = Photo
    context_object_name = 'photo'
    template_name = 'delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_photo'

    def test_func(self, **kwargs):
        photo = Photo.objects.get(pk=self.kwargs.get('pk'))
        if self.request.user == photo.author or self.request.user.has_perm('webapp.change_photo'):
            return True
        else:
            return False

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MySite{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar-my">
    <div class="container">
        <ul class="menu">
            <li><a href="{% url 'webapp:index' %}">Home</a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            {% block menu %}{% endblock %}
            <li class="menu-right">
                <ul>
                    {% if request.user.is_authenticated %}
                        <li style="color: darkblue;">Hello, {{request.user}}!</li>
                        <li><a href="{% url 'webapp:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'webapp:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/create.html
{% extends "base.html" %}
{% block title %}Add Photo{% endblock %}
{% block content %}
    <h2>Add Photo</h2>
    <form method="POST" action='{% url 'webapp:add_photo' %}' enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Add' %}
    </form>
{% endblock %}

source/webapp/templates/delete.html
{% extends "base.html" %}
{% block title %}Delete Photo{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:photo_detail' photo.pk %}">Details</a></li>
{% endblock %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h3>Are you sure want to delete photo?</h3>
            <form method="POST" action="{% url "webapp:delete_photo" photo.pk %}" class="text-center">
                {% csrf_token %}
                <div class="card mb-3" style="max-width: 540px; justify-items: center">
                  <div class="row no-gutters" style="align-items: center">
                    <div class="col-md-4">
                      <img src="{{ photo.photo.url }}" class="card-img" alt="photo">
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                          <p class="card-note">{{ photo.note }}</p>
                          <p class="card-note">Created by: {{ photo.author }}</p>
                          <p class="card-note">Created at: {{ photo.created_at }}</p>
                          <p class="card-like">Likes: {{ photo.like }}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4">
                <button type="submit" class="btn btn-dark" value="Подтвердить">Yes</button>
                <button type="submit" class="btn btn-dark" value="Submit"><a href="{% url 'webapp:photo_detail' photo.pk %}">No</a></button>
            </form>
        </div>
    </div>
{% endblock %}

source/webapp/templates/detail.html
{% extends 'base.html' %}
{% block menu %}
    {% if perms.webapp.change_photo or request.user == photo.author %}
        <li><a href="{% url 'webapp:edit_photo' photo.pk %}">Edit Photo</a></li>
    {% endif %}
    {% if perms.webapp.delete_photo or request.user == photo.author %}
        <li><a href="{% url 'webapp:delete_photo' photo.pk %}">Delete Photo</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card  mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{ photo.photo.url }}" class="card-img" alt="photo">
        </div>
        <div class="col-md-8">
          <div class="card-body">
              <p class="card-note">{{ photo.note }}</p>
              <p class="card-note">Created by: {{ photo.author }}</p>
              <p class="card-note">Created at: {{ photo.created_at }}</p>
              <p class="card-like">Likes: {{ photo.like }}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="comment-list">
        {% for comment in photo.photo_comment.all %}
            <hr>
            <div class="comment">
                <p><b>{{ forloop.counter }}. {{ comment.text }}</b></p>
                <p>Created by - {{ comment.comment_author }},  date: {{ comment.comment_created_at|date:'d.m.Y H:i:s'}}</p>
                {% if comment.comment_author == request.user%}
                    <a href="#" id="delete_comment" onclick="deleteComment({{ comment.pk }})">Delete</a>{#                    <button type="button" class="btn btn-primary" onclick="deleteComment({{ comment.pk }})">Delete</button>#}
                {% endif %}
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}
    </div>
    <hr>
    {{ request.user.is_authentificated }}
    {% if request.user.is_authentificated %}
        <h3>You can add comment below</h3>
        <form action="#" method="POST" id="add_comment">
        {% csrf_token %}
            <div>
                <input type="hidden" id="photo_id" value="{{ photo.pk }}" style="width: 100%;">
                <input type="text" id="comment" style="width: 100%;">
            </div>
                <button type="submit" class="btn btn-primary mt-3">Add</button>
        </form>
    {% endif %}
{% endblock %}

source/webapp/templates/edit.html
{% extends "base.html" %}
{% block title %}Edit Photo{% endblock %}
{% block content %}
    <h2>Edit Photo</h2>
    <form method="POST" action='{% url 'webapp:edit_photo' photo.pk %}' enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Update' %}
    </form>
{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block menu %}
    {% if request.user.is_authenticated %}
        <li><a href="{% url 'webapp:add_photo' %}">Add Photo</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card-deck">
        {% for photo in photos %}
          <div class="card">
              <a href="{% url 'webapp:photo_detail' photo.pk %}"><img src="{{ photo.photo.url }}" class="card-img-top" alt="photo"></a>
            <div class="card-body">
                <p class="card-note">{{ photo.note }}</p>
                <p class="card-note">Created by: {{ photo.author }}</p>
                <p class="card-note">Created at: {{ photo.created_at }}</p>
                <p class="card-like">Likes: {{ photo.like }}</p>
            </div>
          </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}

{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}
        {% if field.field.required %}
            <span class="form-required">*</span>
        {% endif %}
    </label></p>
    {% if field.errors %}
        <p>{{ field|add_class:'field-error form-control' }}</p>
    {% else %}
        <p>{{ field|add_class:'form-control' }}</p>
    {% endif %}
    {% for error in field.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
{% endfor %}

<p class="text-center"><input type="submit" value="{{ button_text }}" class="btn btn-primary"></p>